from aemet import Aemet
aemet_client = Aemet(api_key="eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJlbnJpMTk5OEBob3RtYWlsLmNvbSIsImp0aSI6ImVjNjg3NWQ1LWM2YjctNDYwOS04MTkzLWFhODhhOTAxNDNjYyIsImlzcyI6IkFFTUVUIiwiaWF0IjoxNjg3NzExNTE5LCJ1c2VySWQiOiJlYzY4NzVkNS1jNmI3LTQ2MDktODE5My1hYTg4YTkwMTQzY2MiLCJyb2xlIjoiIn0.L8SgqaOx-4zFWeLl3T9RTkYBep9YoYGCeOInqLiHCAI")

print(aemet_client)